package com.example.sdm_eco_mileage.utils

import com.jwplayer.pub.api.license.LicenseUtil

var accessToken: String = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwibmlja25hbWUiOiLstZzqsr3tm4giLCJleHAiOjE2NDcyNTQzOTksInVzZXJpZCI6ImlhbkBiaWd0ZWFtLmNvLmtyIiwiZW1haWwiOiJpYW5AYmlndGVhbS5jby5rciJ9.2vjgxMUDjR8PRlfR3CWTu7BG_sozH1hQS5PTM442Dxc"
var userid: String = ""
