package com.example.sdm_eco_mileage.utils

import com.jwplayer.pub.api.license.LicenseUtil

val accessToken: String = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwibmlja25hbWUiOiLstZzqsr3tm4giLCJleHAiOjE2NDcwMTIxNzUsInVzZXJpZCI6ImlhbkBiaWd0ZWFtLmNvLmtyIiwiZW1haWwiOiJpYW5AYmlndGVhbS5jby5rciJ9.u4lvZIVhRnXKa6zflQYqFzzo7y_6hmuGflUrzHbH1Gg"
